translate Contributing-To-ROS-2-Documentation
ROS-Spanish-Users-Group/ros2_documentation pull request #13
Opened 2023-01-16 16:45 UTC by jsduenass

Primera traducción de la lista de páginas especificadas en #11

2023-01-18 16:03 UTC, fmrico requested changes

2023-01-18 16:03 UTC, fmrico commented on source/The-ROS2-Project/Contributing/Code-Style-Language-Versions.rst
> +* Elimine el requisito de que todos los miembros de la clase sean privados y, por lo tanto, requieran accessors
Elimine->Elimina

(voz "de tú" en lugar de voz "de usted"

2023-01-18 16:03 UTC, fmrico commented on source/The-ROS2-Project/Contributing/Code-Style-Language-Versions.rst
> +* Utilice los comentarios ``///`` y ``/** */`` para propósitos de *documentación* y comentarios de estilo ``//`` para notas y comentarios generales
Utiliza

2023-01-18 16:03 UTC, fmrico commented on source/The-ROS2-Project/Contributing/Code-Style-Language-Versions.rst
> +* No coloque 1 espacio antes de ``public:``, ``private:`` o ``protected:``, es más consistente que todas las sangrías sean múltiplos de 2
Coloques

2023-01-18 16:03 UTC, fmrico commented on source/The-ROS2-Project/Contributing/Code-Style-Language-Versions.rst
> +  * Si usa 2 espacios antes, indenta otras declaraciones de clase con 2 espacios adicionales
usas

2023-01-18 16:03 UTC, fmrico commented on source/The-ROS2-Project/Contributing/Code-Style-Language-Versions.rst
> +  * Si usa 2 espacios antes, indenta otras declaraciones de clase con 2 espacios adicionales
usas

2023-01-18 16:03 UTC, fmrico commented on source/The-ROS2-Project/Contributing/Code-Style-Language-Versions.rst
> +* Nunca agregue espacios en blanco a las plantillas anidadas
agregues

2023-01-18 16:03 UTC, fmrico commented on source/The-ROS2-Project/Contributing/Code-Style-Language-Versions.rst
> +* Se Preferiré funciones con ``set(PARENT_SCOPE)`` a macros.
Se prefiere

2023-01-18 16:03 UTC, fmrico commented on source/The-ROS2-Project/Contributing/Contributing-To-ROS-2-Documentation.rst
> +También puede ejecutar las pruebas de documentación localmente (usando `doc8 <https://github.com/PyCQA/doc8>`_) con el siguiente comando:
puedes

2023-01-18 16:03 UTC, fmrico commented on source/The-ROS2-Project/Contributing/Contributing-To-ROS-2-Documentation.rst
> +Para ver el resultado, abra ``build/html/index.html`` en su navegador.
abre

2023-01-18 16:03 UTC, fmrico commented on source/The-ROS2-Project/Contributing/Contributing-To-ROS-2-Documentation.rst
> +Para construir el sitio para todas las ramas, escriba ``make multiversion`` desde la rama ``rolling``.
escribe

2023-01-18 16:03 UTC, fmrico commented on source/The-ROS2-Project/Contributing/Contributing-To-ROS-2-Documentation.rst
> +Para verificar si hay enlaces rotos en el sitio, ejecute:
ejecuta

2023-01-18 16:04 UTC, fmrico commented
Hola @jsduenass 

Muchas gracias!! Está muy bien. Solamente hay que cambiar algunas voces de palabras para ser coherente.

2023-01-18 23:04 UTC, jsduenass commented
@fmrico listas las correciones.
 Tambien debido a los cambios que tuvo rolling iba a haber un conflicto. Por lo que hice un commit de merge resolviendo el conflicto. No se esta fue la mejor solución

2023-01-19 18:53 UTC, fmrico approved these changes

2023-01-19 18:54 UTC, merged

2023-01-19 18:54 UTC, fmrico commented
merging!!! :rocket: