Translation Beginner CLI Tools part-0
ROS-Spanish-Users-Group/ros2_documentation pull request #15
Opened 2023-01-18 13:13 UTC by MartinNievas

Hola,

se agregan las traducciones de las siguientes páginas de Beginner CLI Tools como se propuso en #5 

- Introducing-Turtlesim
- Understanding-ROS2-Nodes
- Understanding-ROS2-Topics
- Understanding-ROS2-Parameters

Saludos

2023-01-18 16:10 UTC, fmrico requested changes

2023-01-18 16:10 UTC, fmrico commented on source/Tutorials/Beginner-CLI-Tools/Introducing-Turtlesim/Introducing-Turtlesim.rst
> +Como siempre, no olvide ejecutar `source` con el archivo de setup en cada terminal nueva que abra, como se describe en el :doc:`tutorial previo<../Configuring-ROS2-Environment>`.
Trata de usar la voz "de tú" en lugar de "de usted", para ser coherente con toda la documentación. Te las voy a marcar, pero alguna se me va a pasar

"no olvide" -> "no olvides"

2023-01-18 16:10 UTC, fmrico commented on source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Topics/Understanding-ROS2-Topics.rst
> +Que regresará:
"regresará" -> "devolverá"?

De hecho, creo que has puesto devolver en otros sitios

2023-01-18 16:10 UTC, fmrico commented on source/Tutorials/Beginner-CLI-Tools/Introducing-Turtlesim/Introducing-Turtlesim.rst
> +Para iniciar turtlesim, ingresa el siguiente comando en la terminal:
"Ingresar" -> "Introducir"?

2023-01-18 16:12 UTC, fmrico commented
Hola @MartinNievas 

Muchas gracias!! Tiene muy buena pinta, solo te he puesto unas pocas cuestiones. Parece que hay también algún problema con los tests, que tiene que ver con las longitudes de los subrayados de las secciones.

```
/home/runner/work/ros2_documentation/ros2_documentation/source/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Topics/Understanding-ROS2-Topics.rst:8: D000 Title underline too short.
/home/runner/work/ros2_documentation/ros2_documentation/source/Tutorials/Beginner-CLI-Tools/Introducing-Turtlesim/Introducing-Turtlesim.rst:138: D000 Title underline too short.
/home/runner/work/ros2_documentation/ros2_documentation/source/Tutorials/Beginner-CLI-Tools/Introducing-Turtlesim/Introducing-Turtlesim.rst:138: D000 Title underline too short.
/home/runner/work/ros2_documentation/ros2_documentation/source/Tutorials/Beginner-CLI-Tools/Introducing-Turtlesim/Introducing-Turtlesim.rst:175: D000 Title underline too short.
/home/runner/work/ros2_documentation/ros2_documentation/source/Tutorials/Beginner-CLI-Tools/Introducing-Turtlesim/Introducing-Turtlesim.rst:175: D000 Title underline too short.
/home/runner/work/ros2_documentation/ros2_documentation/source/Tutorials/Beginner-CLI-Tools/Introducing-Turtlesim/Introducing-Turtlesim.rst:252: D000 Title underline too short.
/home/runner/work/ros2_documentation/ros2_documentation/source/Tutorials/Beginner-CLI-Tools/Introducing-Turtlesim/Introducing-Turtlesim.rst:252: D000 Title underline too short.
```

2023-01-20 11:58 UTC, MartinNievas commented
Hola @fmrico 
Gracias por tu tiempo para revisar este MR :)

Voy a realizar las correcciones

2023-01-23 17:19 UTC, fmrico commented
Gracias a tí por dedicarle tiempo a esto ;)

2023-02-20 18:36 UTC, fmrico approved these changes

2023-03-18 07:04 UTC, merged

2023-03-18 07:04 UTC, fmrico commented
Gracias!!!