Traduccion Build-Farms.rst
ROS-Spanish-Users-Group/ros2_documentation pull request #27
Opened 2023-03-03 19:10 UTC by rje1974

Hola.. Era un probelma mio y tan tonto que me da vergüenza comentarlo. Me podrían confirmar si cumplí con los pasos necesarios..?
Saludos..

2023-03-14 18:17 UTC, rje1974 commented
@fmrico me prodrías confirmar si estuvo bien lo que hice, porque tengo dudas y no quiero ir rompiendo cosas por ahí.. Saludos..

2023-03-14 20:14 UTC, fmrico commented
Yo el texto lo veo bien. Vamos a ver lo que dice el CI. Si pasa, mañana lo termino de revisar

Gracias!!!

2023-03-18 07:10 UTC, fmrico commented
Hola @rje1974 

Parece que hay algunos errores:

```
/home/runner/work/ros2_documentation/ros2_documentation/source/The-ROS2-Project/Contributing/Build-Farms.rst:7: D000 Title overline too short.
/home/runner/work/ros2_documentation/ros2_documentation/source/The-ROS2-Project/Contributing/Build-Farms.rst:26: D000 Title underline too short.
/home/runner/work/ros2_documentation/ros2_documentation/source/The-ROS2-Project/Contributing/Build-Farms.rst:39: D000 Title underline too short.
/home/runner/work/ros2_documentation/ros2_documentation/source/The-ROS2-Project/Contributing/Build-Farms.rst:72: D000 Title underline too short.
/home/runner/work/ros2_documentation/ros2_documentation/source/The-ROS2-Project/Contributing/Build-Farms.rst:72: D000 Title underline too short.
/home/runner/work/ros2_documentation/ros2_documentation/source/The-ROS2-Project/Contributing/Build-Farms.rst:89: D000 Enumerated list ends without a blank line; unexpected unindent.
/home/runner/work/ros2_documentation/ros2_documentation/source/The-ROS2-Project/Contributing/Build-Farms.rst:90: D000 Block quote ends without a blank line; unexpected unindent.
/home/runner/work/ros2_documentation/ros2_documentation/source/The-ROS2-Project/Contributing/Build-Farms.rst:89: D000 Unknown target name: "manifiesto del paquete".
/home/runner/work/ros2_documentation/ros2_documentation/source/The-ROS2-Project/Contributing/Build-Farms.rst:91: D000 Unknown target name: "ejecutar los trabajos de lanzamiento localmente".
/home/runner/work/ros2_documentation/ros2_documentation/source/The-ROS2-Project/Contributing/Build-Farms.rst:95: D000 Unknown target name: "manifiesto del paquete".
```

2023-05-19 01:46 UTC, jsduenass commented
Hola @rje1974 
Para comentarte un par de cosas de errores que se generaron al momento de la traducción 
1. titulos: En archivos .rst (reStructuredText) los titulos y subtitulos vienen subrrallados y el subrrallado debe tener la misma longitud.

``` 
Trabajos e implementación
-------------------------
``` 
En lugar de 
```
Trabajos e implementación
------------
``` 

2. referencias: cosas de la forma  ``package manifest\`_ son referencias a otras secciones de la documentación por lo que no deben traducirce

2023-05-19 02:13 UTC, jsduenass requested changes
Se necesita corregir las 2  cosas que mencione con anterioridad que generar errores
1. Titulos
2. Referencias


Si quieres ayuda realizando estos cambios, yo podria realizarlos, pero para ello tienes que cambiar la configuración del pull request para [permitir edición de los maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests). Nota: esto permitira que realice cambios sobre  tu fork especificamente la rama que usaste para este pull request que en este caso fue rolling.

2023-05-22 08:21 UTC, fmrico commented
Hola @jsduenass 

Yo lo veo seleccionado. Hay un tick verde al lado del " Maintainers are allowed to edit this pull request." en este PR

Gracias!!

2023-05-22 16:36 UTC, jsduenass approved these changes

2023-05-22 16:39 UTC, merged

2023-05-22 16:45 UTC, jsduenass commented
Muchas gracias @fmrico no me habia dado cuenta, ya quedo el merge.